<?php
/*
AUTHOR:- RITHUNAND [BENCHAMXD]
CHANNEL:- @INDUSBOTS 
THIS REPO IS LICENCED WITH GENERAL PUBLIC LICENSE VERSION:3.0
(c) RITHUNAND K
*/
$TG_BOT_TOKEN = $_ENV['TG_BOT_TOKEN'];
$BOT_NAME = $_ENV['BOT_NAME'];
$BOT_USERNAME = $_ENV['BOT_USERNAME'];

?>
