<?php
/*
AUTHOR:- Bawwa Official
CHANNEL:- @HARP_Tech
THIS REPO IS LICENCED WITH GENERAL PUBLIC LICENSE VERSION:3.0
(c) Bawwa
*/
$TG_BOT_TOKEN = $_ENV['TG_BOT_TOKEN'];
$BOT_NAME = $_ENV['BOT_NAME'];
$BOT_USERNAME = $_ENV['BOT_USERNAME'];

?>
